# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff73b9325d52fbfbbeaf67fc62f02d69479f8a4af6cbfc5dc6babb81e728ae302b9816c7f0de30f7e5a6e13340bfa396d7d8637f4264e33a1d19edd32efe09f0

test:
  secret_key_base: 4e079eaecb97d30f7c6010394df6e9a9a7479f619587d042a7f3272ce6588ae5d0fb3ea8f743962f0b56916c5a849e186e5fe452fbe166822fc8acbe86ac6668

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
